import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';
import { ClerkProvider } from '@clerk/nextjs';
import { Suspense } from 'react';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Yogesh Estate',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.png', // This looks into the public folder
    apple: '/logo.png', // For iOS home screen icons
  },
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang='en'>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Suspense fallback={<div className="h-20 bg-purple-200" />}> 
            <Header />
          </Suspense>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
